name: C/C++ CI

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-24.04
    container: devkitpro/devkitarm

    steps:
      - uses: actions/checkout@v4
      - name: make
        run: make all
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ダウンロード
          compression-level: 0
          path: ./

      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v5
        with:
          path: ./
          key: ${{ runner.os }}-primes
              